import { z } from "zod";

export const homeHubTileUpsertSchema = z.object({
  id: z.string().optional(),
  slug: z.string().trim().min(2).max(80),
  title: z.string().trim().min(2).max(80),
  href: z.string().trim().min(1).max(300),
  description: z.string().trim().min(4).max(280),
  imageUrl: z.string().trim().min(1).max(500),
  altText: z.string().trim().min(4).max(180),
  hintText: z.string().trim().min(4).max(180),
  tone: z.enum(["agro", "territory"]).default("agro"),
  sortOrder: z.coerce.number().int().min(0).max(999).default(0),
  isActive: z.boolean().default(true),
});

export type HomeHubTileUpsertInput = z.infer<typeof homeHubTileUpsertSchema>;

export const DEFAULT_HOME_HUB_TILES = [
  {
    slug: "embutidos-y-productos-carnicos",
    title: "Embutidos y productos cárnicos",
    href: "/categorias/embutidos-y-productos-carnicos",
    description: "5 subcategorías. Pieza, loncheados de caza y tacos gourmet.",
    imageUrl: "/categories/embutidos-y-productos-carnicos.png",
    altText: "Jamón curado en lonchas y chorizos artesanos sobre tabla de madera",
    hintText: "Abrir la categoría de embutidos y productos cárnicos",
    tone: "agro" as const,
    sortOrder: 10,
    isActive: true,
  },
  {
    slug: "quesos-y-lacteos",
    title: "Quesos y lácteos",
    href: "/categorias/quesos-y-lacteos",
    description: "4 subcategorías. Oveja, cabra y mezcla de obradores cercanos.",
    imageUrl: "/categories/quesos-y-lacteos.png",
    altText: "Cuñas de queso de la comarca con miel y nueces",
    hintText: "Abrir la categoría de quesos y lácteos",
    tone: "agro" as const,
    sortOrder: 20,
    isActive: true,
  },
  {
    slug: "vinos",
    title: "Vinos",
    href: "/categorias/vinos",
    description: "4 subcategorías. Tintos, blancos y rosados del entorno.",
    imageUrl: "/categories/vinos.png",
    altText: "Botellas de vino tinto, blanco y rosado frente a un viñedo",
    hintText: "Abrir la categoría de vinos",
    tone: "agro" as const,
    sortOrder: 30,
    isActive: true,
  },
  {
    slug: "licores",
    title: "Licores",
    href: "/categorias/licores",
    description: "2 subcategorías. Orujos y licores de tradición.",
    imageUrl: "/categories/licores.png",
    altText: "Botellas de orujo y licores tradicionales en una barra rústica",
    hintText: "Abrir la categoría de licores",
    tone: "agro" as const,
    sortOrder: 40,
    isActive: true,
  },
  {
    slug: "turismo-rural",
    title: "Turismo rural",
    href: "/alojamientos",
    description: "Alojamientos de la sierra. Reserva en su canal habitual.",
    imageUrl: "/categories/productos-tradicionales.png",
    altText: "Productos de la sierra que ilustran el territorio: acceso a casas rurales y alojamientos",
    hintText: "Ver alojamientos rurales. La reserva se hace fuera del marketplace",
    tone: "territory" as const,
    sortOrder: 50,
    isActive: true,
  },
  {
    slug: "packs",
    title: "Packs",
    href: "/packs",
    description: "Noche + lote gourmet. La estancia fuera; el lote en el carrito.",
    imageUrl: "/categories/miel-y-productos-apicolas.png",
    altText: "Miel y elaboraciones locales que componen las cestas y packs gourmet",
    hintText: "Ver packs y cestas gourmet para comprar el lote en el marketplace",
    tone: "territory" as const,
    sortOrder: 60,
    isActive: true,
  },
];
